name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Game package name'
        required: true
        default: 'com.dts.freefiremax'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup NDK
        run: |
          echo "y" | sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
      - name: Build module
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
          chmod +x gradlew
          ./gradlew :module:assembleRelease
        env:
          PACKAGE_NAME: ${{ github.event.inputs.package_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-il2cppdumper
          path: out/*.zip
          
