name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Game package name'
        required: true
        default: 'com.dts.freefiremax'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
      - name: Build module
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_NDK_ROOT" >> local.properties
          chmod +x gradlew
          ./gradlew :module:assembleRelease
        env:
          PACKAGE_NAME: ${{ github.event.inputs.package_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-il2cppdumper
          path: out/*.zip
